## Specify a base image to build from.
FROM debian:bullseye-slim

## Set command to run when container starts.
ENTRYPOINT [ "echo" ]

## OPTIONAL: Provide arguments to use with above command.
CMD [ "Hello", "World!" ]
