version: '3'

services:
  cln-alice:
    build: .
    image: cln-demo:latest
    container_name: cln-alice
    hostname: cln-alice
    networks:
      - polar
    restart: unless-stopped
    tty: true
    volumes:
      - alice-data:/root/.lightning:rw
      - ./config/alice:/config:rw
      - ./plugins:/plugins:rw

  cln-bob:
    build: .
    image: cln-demo:latest
    container_name: cln-bob
    hostname: cln-bob
    networks:
      - polar
    restart: unless-stopped
    tty: true
    volumes:
      - bob-data:/root/.lightning:rw
      - ./config/bob:/config:rw
      - ./plugins:/plugins:rw

networks:
  polar:
    name: 1_default

volumes:
  alice-data:
    name: cln_data_alice
  bob-data:
    name: cln_data_bob
